//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPInitial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userevent
    {
        public int AppointmentID { get; set; }
        public int EventID { get; set; }
        public string Subject { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Eircode { get; set; }
        public string PhoneNumber { get; set; }
        public string EmployeeID { get; set; }
    }
}
