using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPInitial.Models;

//Controller to manage default landing page, auto-generated by ASP.NET.
namespace FYPInitial.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (User.IsInRole("Customer") | User.IsInRole("Admin") | User.IsInRole("Employee"))
            {
                return RedirectToAction("Index", "User");
            }
            else
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

      

       

       
    }


}
