// <auto-generated />
namespace FYPInitial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changephonenumtostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changephonenumtostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101539406_Change phone num to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
